{"uid":"738c8b42a4d022d8","name":"Поиск в яндексе","fullName":"test.test_tensor.TensorTestCase#test_search","historyId":"6bc54fbf095856b02ce30f6849fa7bbe","time":{"start":1659191734751,"stop":1659191738711,"duration":3960},"status":"failed","statusMessage":"AssertionError: Открылась страница с капчей\nassert False","statusTrace":"self = <test.test_tensor.TensorTestCase testMethod=test_search>\n\n    def setUp(self):\n        self.browser_setup()\n>       self.navigate_to_home_page()\n\ntest/test_tensor.py:17: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <test.test_tensor.TensorTestCase testMethod=test_search>\n\n    def navigate_to_home_page(self):\n        self.hp = Home_Page()\n        self.hp.navigate()\n        try:\n            assert Captcha_Page().form.checkbox.element.visible\n        except splinter.exceptions.ElementDoesNotExist:\n            pass\n        else:\n>           assert False, \"Открылась страница с капчей\"\nE           AssertionError: Открылась страница с капчей\nE           assert False\n\ntest/test_tensor.py:32: AssertionError","flaky":false,"newFailed":true,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_unittest_setUpClass_fixture_TensorTestCase","time":{"start":1659191720016,"stop":1659191720017,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"hasContent":false,"stepsCount":0,"attachmentsCount":0}],"testStage":{"status":"failed","statusMessage":"AssertionError: Открылась страница с капчей\nassert False","statusTrace":"self = <test.test_tensor.TensorTestCase testMethod=test_search>\n\n    def setUp(self):\n        self.browser_setup()\n>       self.navigate_to_home_page()\n\ntest/test_tensor.py:17: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <test.test_tensor.TensorTestCase testMethod=test_search>\n\n    def navigate_to_home_page(self):\n        self.hp = Home_Page()\n        self.hp.navigate()\n        try:\n            assert Captcha_Page().form.checkbox.element.visible\n        except splinter.exceptions.ElementDoesNotExist:\n            pass\n        else:\n>           assert False, \"Открылась страница с капчей\"\nE           AssertionError: Открылась страница с капчей\nE           assert False\n\ntest/test_tensor.py:32: AssertionError","steps":[{"name":"Перейти на главную страницу Яндекса","time":{"start":1659191735831,"stop":1659191735832,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"hasContent":false,"stepsCount":0,"attachmentsCount":0}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"hasContent":true,"stepsCount":1,"attachmentsCount":0},"afterStages":[{"name":"_unittest_setUpClass_fixture_TensorTestCase::0","time":{"start":1659191738733,"stop":1659191738733,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"hasContent":false,"stepsCount":0,"attachmentsCount":0}],"labels":[{"name":"severity","value":"normal"},{"name":"parentSuite","value":"test"},{"name":"suite","value":"test_tensor"},{"name":"subSuite","value":"TensorTestCase"},{"name":"host","value":"fv-az173-277"},{"name":"thread","value":"2728-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test.test_tensor"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":1,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"eac92800ab65ae10","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/34//#testresult/eac92800ab65ae10","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5722e09e40>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1659191418401,"stop":1659191418419,"duration":18}},{"uid":"a6f75d64911bcb2f","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/33//#testresult/a6f75d64911bcb2f","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fea7fb8bb20>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1659191268520,"stop":1659191268539,"duration":19}},{"uid":"3f611ceee3ba9edd","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/31//#testresult/3f611ceee3ba9edd","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7ddcbdfb80>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1659191009672,"stop":1659191009690,"duration":18}}]},"tags":[]},"source":"738c8b42a4d022d8.json","parameterValues":[]}