{"9214267beedc59fe8c2f8d4f710a67a6":{"statistic":{"failed":7,"broken":4,"skipped":0,"passed":4,"unknown":0,"total":15},"items":[{"uid":"6afdbea843b228ea","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/48//#testresult/6afdbea843b228ea","status":"passed","time":{"start":1659262821723,"stop":1659262837547,"duration":15824}},{"uid":"430546dd84052dff","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/47//#testresult/430546dd84052dff","status":"passed","time":{"start":1659262464305,"stop":1659262483370,"duration":19065}},{"uid":"a9c1d0fb43ad55b4","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/46//#testresult/a9c1d0fb43ad55b4","status":"passed","time":{"start":1659260637343,"stop":1659260652263,"duration":14920}},{"uid":"c71206fe4f3ce831","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/45//#testresult/c71206fe4f3ce831","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4481ea710>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1659258678335,"stop":1659258678355,"duration":20}},{"uid":"effc26a9f5e195ba","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/44//#testresult/effc26a9f5e195ba","status":"passed","time":{"start":1659255963879,"stop":1659255982844,"duration":18965}},{"uid":"a284cdbde6dfea35","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/43//#testresult/a284cdbde6dfea35","status":"failed","statusDetails":"AssertionError: Текущая картинка не равна эталонной","time":{"start":1659206677564,"stop":1659206695191,"duration":17627}},{"uid":"c1e091dab22d7fab","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/42//#testresult/c1e091dab22d7fab","status":"failed","statusDetails":"AssertionError: Текущая картинка не равна эталонной","time":{"start":1659199986223,"stop":1659200003873,"duration":17650}},{"uid":"5d6443300745f2e8","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/41//#testresult/5d6443300745f2e8","status":"failed","statusDetails":"AssertionError","time":{"start":1659196928824,"stop":1659196944449,"duration":15625}},{"uid":"6de857efb89c5249","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/39//#testresult/6de857efb89c5249","status":"failed","statusDetails":"AssertionError","time":{"start":1659194295271,"stop":1659194313587,"duration":18316}},{"uid":"a90370f86e506b68","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/38//#testresult/a90370f86e506b68","status":"failed","statusDetails":"AssertionError","time":{"start":1659193948639,"stop":1659193962862,"duration":14223}},{"uid":"474236cc787eb95b","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/37//#testresult/474236cc787eb95b","status":"failed","statusDetails":"AssertionError","time":{"start":1659193812291,"stop":1659193828075,"duration":15784}},{"uid":"ccfe1d233497285e","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/36//#testresult/ccfe1d233497285e","status":"failed","statusDetails":"AssertionError","time":{"start":1659191720033,"stop":1659191734699,"duration":14666}},{"uid":"8e0495c32f8aaff9","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/34//#testresult/8e0495c32f8aaff9","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5723152d70>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1659191418119,"stop":1659191418151,"duration":32}},{"uid":"a4ec9ca0d56c6061","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/33//#testresult/a4ec9ca0d56c6061","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fea7fed6170>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1659191268197,"stop":1659191268219,"duration":22}},{"uid":"db2ce8f094a32e74","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/31//#testresult/db2ce8f094a32e74","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7ddcf2a1d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1659191009401,"stop":1659191009421,"duration":20}}]},"6bc54fbf095856b02ce30f6849fa7bbe":{"statistic":{"failed":5,"broken":4,"skipped":0,"passed":6,"unknown":0,"total":15},"items":[{"uid":"7c2b3a96e14429b4","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/48//#testresult/7c2b3a96e14429b4","status":"failed","statusDetails":"AssertionError: Открылась страница с капчей\nassert False","time":{"start":1659262837550,"stop":1659262841839,"duration":4289}},{"uid":"20a36651f92527f4","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/47//#testresult/20a36651f92527f4","status":"passed","time":{"start":1659262483372,"stop":1659262492523,"duration":9151}},{"uid":"4b6a0ab9426370c4","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/46//#testresult/4b6a0ab9426370c4","status":"failed","statusDetails":"AssertionError: Открылась страница с капчей\nassert False","time":{"start":1659260652268,"stop":1659260656011,"duration":3743}},{"uid":"af5ff71f222815b7","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/45//#testresult/af5ff71f222815b7","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd447e6f280>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1659258678618,"stop":1659258678636,"duration":18}},{"uid":"cf36edd120614426","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/44//#testresult/cf36edd120614426","status":"passed","time":{"start":1659255982847,"stop":1659255993328,"duration":10481}},{"uid":"b8ad27141c1a2f2f","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/43//#testresult/b8ad27141c1a2f2f","status":"passed","time":{"start":1659206695241,"stop":1659206703371,"duration":8130}},{"uid":"97ddcfddabefef54","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/42//#testresult/97ddcfddabefef54","status":"passed","time":{"start":1659200003924,"stop":1659200011945,"duration":8021}},{"uid":"c04c0b21b2d69114","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/41//#testresult/c04c0b21b2d69114","status":"failed","statusDetails":"AssertionError: Открылась страница с капчей\nassert False","time":{"start":1659196944510,"stop":1659196948898,"duration":4388}},{"uid":"f15ecdbddc4c1521","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/39//#testresult/f15ecdbddc4c1521","status":"passed","time":{"start":1659194313648,"stop":1659194321808,"duration":8160}},{"uid":"ec1264e8fcc5b76d","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/38//#testresult/ec1264e8fcc5b76d","status":"failed","statusDetails":"AssertionError: Открылась страница с капчей\nassert False","time":{"start":1659193962930,"stop":1659193966576,"duration":3646}},{"uid":"526d38778751b92c","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/37//#testresult/526d38778751b92c","status":"passed","time":{"start":1659193828152,"stop":1659193837223,"duration":9071}},{"uid":"738c8b42a4d022d8","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/36//#testresult/738c8b42a4d022d8","status":"failed","statusDetails":"AssertionError: Открылась страница с капчей\nassert False","time":{"start":1659191734751,"stop":1659191738711,"duration":3960}},{"uid":"eac92800ab65ae10","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/34//#testresult/eac92800ab65ae10","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5722e09e40>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1659191418401,"stop":1659191418419,"duration":18}},{"uid":"a6f75d64911bcb2f","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/33//#testresult/a6f75d64911bcb2f","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fea7fb8bb20>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1659191268520,"stop":1659191268539,"duration":19}},{"uid":"3f611ceee3ba9edd","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/31//#testresult/3f611ceee3ba9edd","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7ddcbdfb80>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1659191009672,"stop":1659191009690,"duration":18}}]}}